version: "3.7"

services:
    app:
        build: 
            context: .
            dockerfile: ./Dockerfile
        image: django-channels-chat-test
        ports:
            - "8001:8000"
            - "50000:443"
        env_file:
            - .env
        volumes:
          - type: bind
            source: .
            target: /app
        command: "/app/start-dev"
