#!/bin/sh

redis-server --daemonize yes

celery -A djangoChannelsTest.celery worker --loglevel info --detach

python3 manage.py makemigrations chat
python3 manage.py migrate

daphne djangoChannelsTest.asgi:application --port $PORT --bind 0.0.0.0 -v2
